baseURL = 'http://scotlandstats.com/'
languageCode = 'en-us'
title = 'Scotland Stats'
theme = "bloggeri"

paginate = 4


# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

[params]
  description = "My site description"
  
[[menu.main]]
    name = "Categories"
    url = "/categories"
    
[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
    name = "Contact"
    url = "/contact"

[[menu.main]]
  name = "Post"
  url = "/post"

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/HerrNiklasLange"
  pre = "<i class='fab fa-github'></i>"


[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"
